# Generated by Django 5.1.15 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
